name: alemni
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  # GET
  get: 4.6.5
  get_storage: 2.0.3

  # GOOGLE FONTS
  google_fonts: ^2.3.2

  # AUTO SIZE TEXT
  auto_size_text: ^3.0.0

  # INTL
  intl: 0.17.0

  # LOADING ANIMATION
  shimmer: ^2.0.0

  # SVG
  flutter_svg: ^1.1.0

  # CACHED IMAGE
  cached_network_image: ^3.2.1

  # ICON APP
  flutter_launcher_icons: ^0.9.3

  # ZOOM IMAGE VIEW
  photo_view: ^0.14.0

  # PAGE INDICATOR
  smooth_page_indicator: ^1.0.0+2

  # EXPENDABLE PAGE VIEW
  expandable_page_view: ^1.0.14
  
  flutter_localizations:
    sdk: flutter
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  assets: 
    - assets/images/
    - assets/icons/
    - assets/icons/navigation/
    - assets/icons/homepage/
    - assets/icons/course_description/
  uses-material-design: true

